### ISSUE TITLE
Upgrade to latest wagtail release

### ISSUE THREAD

**Issue by obswork** [chrisdev/wagtail-cookiecutter-foundation#257]
Big fan of this project; great to have such a thorough reference of a complete modern python stack.

Hoping to see an upgrade to the latest wagtail release. I can attest to a few things breaking in the process, but still think it'd be worthwhile. I've limited time to work on a pr myself, but I'll probably submit one around the time 1.5 is released if no updates are forthcoming. Nice work again.

**Comment by Parbhat** [comment]
@obswork Great to know you like the project. Wagtail cookiecutter Foundation is compatible with latest Wagtail release 1.4.3. The problem is with fixtures. We are using `Fixtures` for creating example pages. In Future releases, we will drop fixtures and use other techniques to load initial data. Meanwhile, you can upgrade `Wagtail` to 1.4.3 manually after creating projects with this cookiecutter.

**Comment by obswork** [comment]
@Parbhat Yup, I can see that now. I commented out the relevant apps and the update worked perfectly. Thanks for the heads up.
